### ISSUE TITLE
javaws / Web start

### ISSUE THREAD

**Issue by ildar** [AdoptOpenJDK/openjdk9-openj9-releases#2]
is currently missing but still demanded for some legacy apps. Please add.

**Comment by karianna** [comment]
@tellison - Is this an upstream task?

**Comment by stevewallin** [comment]
yes this would be an upstream request as the OpenJDK 9 builds for both HotSpot and Eclipse OpenJ9 do not contain javaws

**Comment by karianna** [comment]
I'm wondering if we simply create alternative builds with JavaFX included as I'm doubtful that OpenJDK would bundle that by default (as they haven't historically).  Not sure about Eclipse OpenJ9 but we could ask over there....

**Comment by stevewallin** [comment]
yes, it might be useful to have a 'fully loaded' build... especially as some of the commercial features land in OpenJDK that have not been available there in the past.

**Comment by tellison** [comment]
@karianna what is the connection you are making between web start and javaFX? or are you just saying we should put in "everything" we can (which doesn't sounds like a great idea to me!).

We can discuss what people would expect to be included in an OpenJDK binary.

**Comment by karianna** [comment]
@tellison Only because I was tired and misread the issue title :-/ - so ignore my comment!

**Comment by karianna** [comment]
This issue was moved to AdoptOpenJDK/openjdk-build#485
